name: blender
version: "4.2"
description: Blender 4.2 LTS

environment:
  BLENDER_VERSION: "4.2"
  PATH: ${BLENDER_HOME:-/opt/blender/4.2}:${PATH}

variants:
  - platform: macos
    environment:
      BLENDER_HOME: /Applications/Blender.app/Contents/MacOS
      BLENDER_RESOURCES: /Applications/Blender.app/Contents/Resources/4.2
  
  - platform: linux
    environment:
      BLENDER_HOME: /opt/blender/4.2
  
  - platform: windows
    environment:
      BLENDER_HOME: C:/Program Files/Blender Foundation/Blender 4.2

commands:
  blender: ${BLENDER_HOME}/blender
