//! Lockfiles and saved contexts for reproducible environments.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result};
use serde::{Deserialize, Deserializer, Serialize};

// ---------------------------------------------------------------------------
// Lockfile
// ---------------------------------------------------------------------------

/// One entry in `Lockfile.pins`.  Carries the version and an optional
/// content hash so drift in shared package directories is detectable.
///
/// Deserializes from either the modern map form
///   `python: { version: "3.11", content_hash: "..." }`
/// or the pre-0.5 string form
///   `python: "3.11"`
/// so older `anvil.lock` files keep working.
#[derive(Debug, Clone, Serialize)]
pub struct Pin {
    pub version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_hash: Option<String>,
}

impl<'de> Deserialize<'de> for Pin {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        #[serde(untagged)]
        enum PinForm {
            Legacy(String),
            Modern {
                version: String,
                #[serde(default)]
                content_hash: Option<String>,
            },
        }
        Ok(match PinForm::deserialize(deserializer)? {
            PinForm::Legacy(version) => Pin {
                version,
                content_hash: None,
            },
            PinForm::Modern {
                version,
                content_hash,
            } => Pin {
                version,
                content_hash,
            },
        })
    }
}

/// Pins package versions for reproducible resolution.
///
/// Stored as `anvil.lock` in the project directory.  When present, the
/// resolver prefers pinned versions over the default "highest matching"
/// strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Lockfile {
    /// Original package requests that produced this lockfile.
    pub requests: Vec<String>,
    /// Pinned versions: package name -> pin entry.
    pub pins: HashMap<String, Pin>,
}

impl Lockfile {
    /// Load a lockfile from a YAML file.
    pub fn load(path: &Path) -> Result<Self> {
        let content = std::fs::read_to_string(path)
            .with_context(|| format!("Failed to read lockfile: {:?}", path))?;
        serde_yaml::from_str(&content)
            .with_context(|| format!("Failed to parse lockfile: {:?}", path))
    }

    /// Write the lockfile to a YAML file.
    pub fn save(&self, path: &Path) -> Result<()> {
        let content = serde_yaml::to_string(self)?;
        let output = format!("# anvil.lock — generated by `anvil lock`, do not edit\n{}", content);
        std::fs::write(path, output)
            .with_context(|| format!("Failed to write lockfile: {:?}", path))
    }

    /// Search for `anvil.lock` starting from CWD and walking upward.
    pub fn find() -> Option<PathBuf> {
        let mut dir = std::env::current_dir().ok()?;
        loop {
            let candidate = dir.join("anvil.lock");
            if candidate.exists() {
                return Some(candidate);
            }
            if !dir.pop() {
                return None;
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Saved context
// ---------------------------------------------------------------------------

/// A fully resolved environment that can be saved, shared, and re-loaded
/// without re-running resolution.  Useful for render farms, CI, and
/// sharing reproducible environments across machines.
#[derive(Debug, Serialize, Deserialize)]
pub struct SavedContext {
    /// Anvil version that created this context.
    pub anvil_version: String,
    /// Unix timestamp (seconds since epoch).
    pub created: u64,
    /// Platform this was resolved on (linux, macos, windows).
    pub platform: String,
    /// Original package requests.
    pub requests: Vec<String>,
    /// Resolved packages in dependency order.
    pub resolved: Vec<ContextPackage>,
    /// Full resolved environment (ready to apply).
    pub environment: HashMap<String, String>,
}

/// A single resolved package entry inside a saved context.
#[derive(Debug, Serialize, Deserialize)]
pub struct ContextPackage {
    pub name: String,
    pub version: String,
}

impl SavedContext {
    /// Load a context from a JSON file.
    pub fn load(path: &Path) -> Result<Self> {
        let content = std::fs::read_to_string(path)
            .with_context(|| format!("Failed to read context: {:?}", path))?;
        serde_json::from_str(&content)
            .with_context(|| format!("Failed to parse context: {:?}", path))
    }

    /// Save the context to a JSON file.
    pub fn save(&self, path: &Path) -> Result<()> {
        let content = serde_json::to_string_pretty(self)?;
        std::fs::write(path, format!("{}\n", content))
            .with_context(|| format!("Failed to write context: {:?}", path))
    }

    /// Get the current platform string.
    pub fn current_platform() -> &'static str {
        if cfg!(target_os = "linux") {
            "linux"
        } else if cfg!(target_os = "macos") {
            "macos"
        } else if cfg!(target_os = "windows") {
            "windows"
        } else {
            "unknown"
        }
    }

    /// Get current unix timestamp.
    pub fn now() -> u64 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .as_secs()
    }
}
